[workspace]
members = [".", "demos/*"]
resolver = "2"

[workspace.dependencies]
bit-set = { version = "0.11", default-features = false }
i_triangle = { git = "https://github.com/iShape-Rust/iTriangle" }
polygon_unionfind = { version = "0.8", features = ["undoredo"] }
rstar = "0.13"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

[package]
name = "anyangle"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde"]

[dependencies]
approx = ">= 0.4.0, < 0.6.0"
bit-set.workspace = true
i_triangle.workspace = true
num-traits = "0.2"
polygon_unionfind.workspace = true
rstar.workspace = true
serde = { workspace = true, optional = true }
