# SPDX-FileCopyrightText: 2026 anyangle contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "astar-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyangle = { path = "../..", features = ["serde"] }
i_triangle.workspace = true
macroquad = "0.4"
rstar.workspace = true
toml = "1.1"
serde.workspace = true
